services:
  flask-app:
    image: python-docker:latest
    container_name: flask-hello-world
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped
